const GET_TODO = "GET_TODO";
const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const DELETE_TODO = "DELETE_TODO";
const UPDATE_TODO = "UPDATE_TODO";

export {GET_TODO, ADD_TODO, TOGGLE_TODO, DELETE_TODO, UPDATE_TODO};